story6App/urls.py
from django.urls import path
from . import views

app_name = 'story6App'

urlpatterns = [
    path('', views.landing, name='landingPage'),
    # dilanjutkan ...
]

story6Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6App.urls')),
    path('story7', include('story7.urls')),
    path('story8', include('story8.urls')),
    path('story9/', include('story9.urls'))
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.home, name='home'),
    # dilanjutkan ...
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.home, name='home'),
    # dilanjutkan ...
]

story9/urls.py
from django.urls import path, include
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
]

story6App/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Status(models.Model):
	status = models.CharField(max_length=300)
	tanggal = models.DateTimeField(default=timezone.now)

story7/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Status(models.Model):
	status = models.CharField(max_length=300)
	tanggal = models.DateTimeField(default=timezone.now)

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story6App/forms.py
from django import forms
from . import models
import datetime

class StatusForm(forms.ModelForm):
	status = forms.CharField(widget=forms.Textarea(attrs={
		"required" : True,
		"placeholder" : "What's happening?",
		}))

	class Meta:
		model = models.Status
		fields = ["status"]
			

story7/forms.py
from django import forms
from . import models

class StatusForm(forms.ModelForm):
	status = forms.CharField(widget=forms.Textarea(attrs={
		"required" : True,
		"placeholder" : "What's happening?",
		}))

	class Meta:
		model = models.Status
		fields = ["status"]
			

story6App/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import StatusForm
from .models import Status

# Create your views here.

def landing(request):
	if request.method == 'POST':
		statform = StatusForm(request.POST)
		if statform.is_valid():
			statform.save()
			return redirect('story6App:landingPage')
	else:
		statform = StatusForm()

	stats = Status.objects.order_by("tanggal")
	listStatus = {
		'form' : statform,
		'status' : stats,
	}
	return render(request, 'landing.html', listStatus)

story7/views.py
from django.shortcuts import render, redirect
from .forms import StatusForm
from .models import Status

# Create your views here.

def home(request):
	if request.method == 'POST':
		statform = StatusForm(request.POST)
		if statform.is_valid():
			statform.save()
			return redirect('story7:home')
	else:
		statform = StatusForm()

	stats = Status.objects.order_by("tanggal")
	listStatus = {
		'form' : statform,
		'status' : stats,
	}
	return render(request, 'homeStory7.html', listStatus)

story8/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
	return render(request, 'story8.html')

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as login_auth, logout as logout_auth

def index(request):
    user = request.user
    if user.is_authenticated:
        return render(request, 'story9.html')        
    else:
        return redirect('story9:login')

def login(request):
    user = request.user
    login_form = AuthenticationForm()
    
    if user.is_authenticated:
        return redirect('story9:index')

    if request.method == "POST":
        login_form = AuthenticationForm(data = request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login_auth(request, user)
            return redirect('story9:index')
    return render(request, 'login.html', {'form':login_form})

def logout(request):
    if request.method == 'POST':
        logout_auth(request)
    return redirect('story9:index')

story6App/templates/landing.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Karin's Profile</title>

    <!-- Latest compiled and minified CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <!-- Custom Fonts -->
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Reem+Kufi">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Abhaya+Libre">

</head>

<body style="background-color: #303030">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container-fluid" style="background-color: white; padding: 20px; max-width: 500px">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <h1>Hello!</h1>
                <h4>How are you, today?</h4>
                
                <form method="POST" class="form">
                    {% csrf_token %}
                    {{ form.status }}
                    <input type="submit" name="Post">
                </form>
            </div>
        </div>
    </div>

    <div class="container-fluid" style="background-color: white; margin-top: 30px; max-width: 500px">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
            {% for stat in status %}
            <div style="margin: 10px">
                <h4>{{ stat.status }}</h4>
                <p>{{ stat.tanggal }}</p>
                <p>-----------------------------</p>
            </div>
            {% endfor %}
            </div>
        </div>
    </div>
    
</body>
</html>

story7/templates/homeStory7.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Story 7</title>

    <!-- Latest compiled and minified CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- Custom Fonts -->
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Reem+Kufi">
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Abhaya+Libre">

    <!-- Custom Files -->
    <link rel="stylesheet" type="text/css" href="{% static '/style7.css' %}">
    <script src="{% static '/story7.js' %}"></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row justify-content-end">
            <div class="col-4" id="form-section">
                <h1>Hello!</h1>
                <h4>How are you, today?</h4>
                
                <form method="POST" class="form">
                    {% csrf_token %}
                    {{ form.status }}
                    <input type="submit" name="Post">
                </form>
            </div>

            <div class="col-4">
                <div class="custom-control custom-switch" id="change">
                    <input type="checkbox" class="custom-control-input" id="customSwitch1" onchange="change()">
                    <label class="custom-control-label" for="customSwitch1" id="toggle">Change Theme</label>
                </div>  
                <div id="accordion">
                    <h3> Activity </h3>
                    <div>
                        <p> - College </p>
                        <p> - College </p>
                        <p> - College </p>
                    </div>
                    <h3> Experience </h3>
                    <div>
                        <p>[2017]  MPK SMAN 1 Jakarta</p>
                        <p>[2017]  SRKP SMAN 1 Jakarta</p>
                        <p>[2019]  Wisuda Genap Fasilkom UI</p>
                    </div>
                    <h3> Achievement </h3>
                    <div>
                        <p> c o m i n g  s o o n</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row justify-content-center" id="status-section">
            <div class="col-4 stat">
            {% for stat in status %}
            <div style="margin: 10px">
                <h4>{{ stat.status }}</h4>
                <p>{{ stat.tanggal }}</p>
                <p>-----------------------------</p>
            </div>
            {% endfor %}  
            </div>   
    </div>
</body>
</html>

story8/templates/story8.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Import Requirements -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            crossorigin="anonymous"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'style8.css' %}" />

    <title>Story 8</title>
</head>

<body>
    <div class="container">
	    <div class="d-flex justify-content-center">
	    	<h1> Find the Book </h1> 
	    </div>

	    <div class="d-flex justify-content-center">
			<div class="row justify-content-md-center">
				<input type="text" id="search" class="form-control" 
					   placeholder="Type the title of a books here..."> 
			</div>
	    </div>
	</div>


	<div class="row justify-content-md-center" id="books">

	</div>


</body>
<script src="{% static 'story8.js' %}"></script>
</html>

story9/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
        <div class='BlockContent test'>
                <div class="form">
                    <center><h2>LOGIN</h2></center>
                    <form action="{% url 'story9:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="unknown"><p>Username</p>{{ form.username }}</div>
                        <div class="unknown"><p>Password</p>{{ form.password }}</div>
                        <div class="unknown test">
                            <button type="submit" class="formbutton">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        
</body>
</html>

story9/templates/story9.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> Story 9 </title>
</head>
<body>
    hello {{ user.username }}
    <form action="{% url 'story9:logout' %}" method="POST">
            {% csrf_token %}
            <div>
                <button type="submit" class="formbutton">Logout</button>
            </div>
    </form>
</body>
</html>